
//“–‚½‚è”»’è‹éŒ`
struct Box {
	int left;
	int top;
	int right;
	int bottom;
};

enum CHAR_ID {
	CHAR_REIMU=0,		CHAR_MARISA,	CHAR_SAKUYA,	CHAR_ALICE,
	CHAR_PATCHOULI,	CHAR_YOUMU,	CHAR_REMILIA,	CHAR_YUYUKO,
	CHAR_YUKARI,		CHAR_SUIKA,	CHAR_UDONGE,	CHAR_AYA,
	CHAR_KOMACHI,		CHAR_IKU,	CHAR_TENSHI,	CHAR_SANAE,
	CHAR_CHIRNO,		CHAR_MEIRIN,	CHAR_UTSUHO,	CHAR_SUWAKO,
	SWR_CHAR_ID_MIN = CHAR_REIMU,	SWR_CHAR_ID_MAX = CHAR_TENSHI,
	SWRS_CHAR_ID_MIN = CHAR_REIMU,	SWRS_CHAR_ID_MAX = CHAR_SUWAKO,
};

bool IsSWR(void);
void AIModeSWR(void);
void AIModeSWRS(void);

const char *ID2Char(CHAR_ID id);
const char *ID2Char2(CHAR_ID id);
